Express API-CRUD_Layered pattern 적용
wecode-bootcamp-korea/42-backend-westagram-2 pull request #10
Opened 2023-01-28 11:55 UTC by sayhihi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- Express API-CRUD_Layered pattern 적용

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- routes, controllers, services, models 모듈화 분리
- routes :  endpoint 분리 및 해당 endpoint와 controller 연결
- controllers : req, res 처리 담당, service layer 호출 및 res 반환
- services : 비즈니스 로직 담당 및 model layer 호출, controller layer로 결과 반환
- models : 데이터베이스 통신 담당 및 service layer로 결과 반환
<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지

1) 유저 등록
![유저등록_layered_pattern](https://user-images.githubusercontent.com/117356735/215263885-82ff278e-c846-4265-9775-95df36ec983a.png)

2) 게시글 등록
![게시글등록_layered_pattern](https://user-images.githubusercontent.com/117356735/215263890-73572368-dfbf-4343-9d9a-99912a850c6e.png)

3) 전체 게시글 조회
![전체게시글조회_layered_pattern](https://user-images.githubusercontent.com/117356735/215263893-9701bab6-f28a-4cc7-95fa-d3f89ceaa3b6.png)

4) 유저 게시글 조회
![유저게시글조회_layered_pattern](https://user-images.githubusercontent.com/117356735/215263895-9d865d62-ec2e-4a4b-b3ba-0e4f72b87540.png)

5) 게시글 수정
![게시글수정_layered_pattern](https://user-images.githubusercontent.com/117356735/215263897-8c6e0a85-61c0-45dc-a938-eeb3417664aa.png)

6) 게시글 삭제
![게시글삭제_layered_pattern](https://user-images.githubusercontent.com/117356735/215263898-25c6b857-b2fc-479e-8c24-9063eab113e2.png)

7) 좋아요 누르기
![좋아요누르기_layered_pattern](https://user-images.githubusercontent.com/117356735/215263900-c1c4cb2d-1634-490f-9bf6-5daef969e088.png)

2. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

1) 유저등록
![유저등록_table_layered_pattern](https://user-images.githubusercontent.com/117356735/215263923-4eaf66f6-4d62-4133-9f12-36e3fdc2ad67.png)

2) 게시글 등록
![게시글등록_table_layered_pattern](https://user-images.githubusercontent.com/117356735/215263924-e912889d-771a-4889-9bbe-26c780e48bbf.png)

3) 게시글 수정
![게시글수정_table_layered_pattern](https://user-images.githubusercontent.com/117356735/215263925-9fe238ec-8115-4d58-97cf-37ca06944cc5.png)

4) 게시글 삭제
![게시글삭제_table_layered_pattern](https://user-images.githubusercontent.com/117356735/215263927-9d9152e4-4e3f-4d18-aa9f-86d7c0215a65.png)

5) 좋아요 누르기
![좋아요누르기_table_layered_pattern](https://user-images.githubusercontent.com/117356735/215263928-b8bb4544-75f4-42a3-b5bd-c6c9a19541ef.png)

<br />

## :: 기타 질문 및 특이 사항
이론적인 개념은 이해가 되었지만 영상 실습과정에서의 코드 작성은 너무 복잡하고 이해가 되지 않아 많이 어려웠습니다. POST 실습만 있어서 다른 메서드는 어떻게 해야할지 감이 잡히지 않고 구글링을 통한 자료도 저에게는 이해할 수가 없어  처음 작성한 레이어드 패턴은 주변의 도움을 받아 작성했습니다. 제가 가장 혼란스러웠던 부분은 service 코드 작성이였습니다. controller 와 Dao는 뚜렷한 특징이 있어 조금이나마 작성을 할 수 있었지만, service는 전달할 내용을 어떻게 작성해야 하는지에 많이 어려움을 겪었습니다. 

처음 작성했던 레이어드 패턴을 완료한 후, 머지되었던 단일파일 과제 백업 자료를 이용해 한 번 더 레이어드 패턴을 연습했고, 처음보다는 레이어드 패턴에 대한 흐름은 대략적으로 이해되었습니다. 그래도 아직은 레이어드 패턴에 대한 이해가 많이 부족하다고 느낍니다ㅠㅠㅠㅠ

2023-01-30 05:13 UTC, kyeongraekim requested changes

2023-01-30 05:13 UTC, kyeongraekim commented on sehee/app.js
> +//     `
- 이곳 이하의 코드는 불필요한 주석처럼 보여지네요! 
- main에 머지되는 코드는 실제 돌아가고 있는 서버의 상용화될 코드라고 생각해주시고, 불필요한 주석처리된 내용은 꼭 사전에 필히 제거해주신 후에 올려주셔야 함을 잊지말아주세요!

2023-01-30 05:13 UTC, kyeongraekim commented on sehee/models/likesDao.js
> +
- 현재 모든 Dao단의 파일에서 해당 내용을 동일하게 사용하고 있음을 확인하실 수 있으실겁니다.
-appDataSource.js 라는 별도의 자바스크립트 파일로 모듈화 하여서 해당내용을 관리해주세요!

2023-01-30 05:13 UTC, kyeongraekim commented on sehee/routes/postsRouter.js
> +router.delete("/remove/:postId", postsController.postRemove);
- RESTful 한 엔드포인트 설계법에서는 update, remove와 같은 동사의 중복 선언을 하지 않습니다. 해당 내용은 put, delete등의 httpMethod로 충분히 확인 가능한 부분이니 동사어구는 지워주세요!

2023-01-30 05:13 UTC, kyeongraekim commented on sehee/routes/userRouter.js
> +router.post("/signup", userController.signUp); //내가 설정한 경로로 작성, 앞에 index에서 받아온 user가 붙어 있음
- 이곳에서도 불필요한 주석이 보이네요!

2023-01-30 05:13 UTC, kyeongraekim commented on sehee/services/likesService.js
> +const likespost = async (postId, userId) => {
- 기본적인 node 기반 함수명 선언 컨벤션은 getPostByUserId 정도의 동사 + 목적어 구조를 취합니다. 해당 내용 전체적으로 살펴주시고 수정해주세요!

2023-01-30 05:13 UTC, kyeongraekim commented on sehee/services/userService.js
> +
- 이곳도 삭제할 내용인지, 남겨둘 내용인지 판단해서 올려주세요!

2023-01-31 04:47 UTC, kyeongraekim requested changes

2023-01-31 04:47 UTC, kyeongraekim commented on sehee/models/postsDao.js
> +    u.id AS userId, u.name AS userName, p.id AS postingId, p.title AS postingTitle, p.content AS postingContent
이곳 전체적으로 line breaking 한 번 확인해주세요!~

2023-02-01 02:30 UTC, sangwoong03 reviewed
세희님~! 추가적인 피드백 확인해주세요

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/controllers/postsController.js
> +    const { title, content, post_image, user_id } = req.body;
camelCase로 수정해주세요!
```suggestion
    const { title, content, postImage, userId } = req.body;
```

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/controllers/likesController.js
> +    console.log(err);
`console.log(err);` 로 에러가 발생했을 때 로그를 확인하는 좋은 코드입니다!

다만 다른 특정 로그와 헷갈릴 수 있기 때문에 아래와 같이 작성할 수 있다는 것도 참고해주세요!

 ```suggestion
    console.error(err);
```

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/controllers/userController.js
> +    if (!name || !email || !password || !profileImage || !phoneNumber) {
profileImage 컬럼은 null 값을 허용하는 것으로 스키마를 설계했는데 content 값이 없어도 Key Error 처리를 하는 이유가 있을까요?

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/routes/index.js
> +router.use("/likes", likesRouter.router);
특정 미들웨어를 적용하는 코드 바로 윗줄에 그에 대한 변수를 할당하는 코드를 작성하는 것도 좋은 방법입니다.

다만, 아래와 같이 작성하면 미들웨어에 사용될 변수 모음 / 미들웨어를 적용하는 코드 모음으로 구분하여 구조를 한눈에 볼 수 있다는 장점이 있습니다.

```suggestion
const userRouter = require("./userRouter");
const postsRouter = require("./postsRouter");
const likesRouter = require("./likesRouter");

router.use("/user", userRouter.router);
router.use("/posts", postsRouter.router);
router.use("/likes", likesRouter.router);
```

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/routes/index.js
> +// 경로 작성
불필요한 주석은 삭제해주세요!

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/routes/postsRouter.js
> +// 게시글 등록
주석을 작성함으로써 어떤 엔드포인트인지 구분하기 용이할 수 있습니다.

하지만 엔드포인트 자체를 명확하게 구분해주면 주석을 작성하고, 코드를 수정했을 때 다시 주석을 수정해야하는 불편함이 사라질 것입니다.

주석은 삭제 후 아래 리뷰를 반영하여 엔드포인트를 수정해주세요!

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/routes/postsRouter.js
> +router.get("/list/:userId", postsController.getPostByUserId);
우선 `routes/index.js` 파일을 통해 해당 엔드포인트에는 `.../posts` resource path가 이미 명시되어 있습니다.

그렇기 때문에 posting 혹은 list와 같은 추가 엔드포인를 다시 명시할 필요가 없습니다.

만약 전체 게시글을 조회한다면 이미 `.../posts` 라는 엔드포인트에서 명시된 resource 자체가 `전체 게시글 = posts`을 가리키고 있어 `list` 라는 resource를 추가적으로 적을 필요가 없습니다.
단일 게시글을 조회할 때도, 게시글을 추가할 때도 마찬가지입니다.

```suggestion
router.post("/", postsController.createPost);
router.get("/", postsController.getPosts);
router.get("/:userId", postsController.getPostByUserId);
```

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/services/postsService.js
> +    await postsDao.createPost(title, content, post_image, user_id);
게시글을 성공적으로 등록했을 때 return 키워드를 통해 해당 함수를 종료하도록 수정해주세요.

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/services/postsService.js
> +// 게시글 등록
주석을 확인해서 전부 지워주세요

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/services/postsService.js
> +
👍👍👍

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/services/postsService.js
> +    await postsDao.updatePost(postId, content);
해당 부분도 업데이트를 성공했을 때의 함수가 종료되도록 return 키워드를 추가해주세요

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/services/postsService.js
> +    await postsDao.deletePost(postId);
해당 부분도 업데이트를 성공했을 때의 함수가 종료되도록 return 키워드를 추가해주세요

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/services/userService.js
> +      throw new Error("PASSWORD_DO_NOT_MEET_CONDITIONS");
마이너 수정사항
```suggestion
      throw new Error("FAILED_TO_VALIDATE_PASSWORD");
```

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/models/userDao.js
> +
해당 파일에서도 불필요한 주석은 삭제해주세요!

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/models/userDao.js
> +      SELECT * FROM
유저에 대한 정보를 모두 가져오지 말고 필요한 컬럼만 가져올 수 있도록 수정해주세요.
```suggestion
      SELECT
         id,
         name,
         email,
         ...
      FROM
```

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/models/postsDao.js
> +  // checkIfUserExistsOrNot,
사용하지 않는 코드는 삭제해주세요!
```suggestion
```

2023-02-01 02:30 UTC, sangwoong03 commented on sehee/models/postsDao.js
> +          AS postings
들여쓰기과 적절한 line-breaking을 적용해주세요
```suggestion
        JSON_ARRAYAGG(
          JSON_OBJECT(
            'postingId', p.id,
            'postingImageUrl',
            p.post_image,
            'postingContent', p.content
          )
        ) AS postings
```

2023-02-02 01:56 UTC, kyeongraekim approved these changes
LGTM!~ 어제 통신시 잡히지 않았던 다양한 에러들을 오후 인증인가 시간 전까지 확실히 잡아보세요!
그리고 프론트와의 통신시험에 앞서서 레이어드 패턴 내에서의 다양한 요소들을 완벽히 이해해주세요!~

2023-02-02 01:56 UTC, merged