[황수영] Assignment 3,4,5: Express API - CRUD
wecode-bootcamp-korea/42-backend-westagram-2 pull request #7
Opened 2023-01-20 06:53 UTC by fromSYHwang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- CRUD 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 게시글 등록하기
- 전체 게시글 조회하기
- 유저id로 유저의 게시글 조회하기
- 데이터베이스 수정 - users 테이블에 프로필 이미지 추가, 회원가입 기능 코드에도 해당 컬럼 추가하여 수정

<br />

## :: 테스트 결과 이미지
![스크린샷 2023-01-20 오후 2 03 02](https://user-images.githubusercontent.com/120305083/213635337-7afc206c-b625-46d9-b236-2eec650f2b44.png)
<img width="1136" alt="스크린샷 2023-01-20 오후 2 05 07" src="https://user-images.githubusercontent.com/120305083/213635342-07d74d0a-b26a-496a-90c4-9ce2c08227fd.png">
![스크린샷 2023-01-20 오후 2 46 59](https://user-images.githubusercontent.com/120305083/213635348-118e5a14-d34c-4e65-8261-7fbf731b8ecd.png)
<img width="1281" alt="스크린샷 2023-01-20 오후 3 29 17" src="https://user-images.githubusercontent.com/120305083/213635358-a18b2338-777a-4d88-91b3-d364f40b1580.png">
<img width="1173" alt="스크린샷 2023-01-20 오후 3 48 20" src="https://user-images.githubusercontent.com/120305083/213635362-22901881-9076-4b5e-aa93-2390a1770dcb.png">

<br />

## :: 기타 질문 및 특이 사항

2023-01-25 05:09 UTC, kyeongraekim requested changes

2023-01-25 05:09 UTC, kyeongraekim commented on sooyoung/app.js
> +app.patch('/post/:postId/edit', async (req, res) => {
- RESTful 한 API 엔드포인트 설계 시 edit과 같이 동사 어구는 patch, put 과 같은 http method로 표현하게 됩니다. 해당 어구는 삭제해주셔도 좋을 것 같네요!

2023-01-25 05:09 UTC, kyeongraekim commented on sooyoung/app.js
> +app.delete('/post/:postId/delete', async (req, res) => {
- 위 update와 관련한 내용으로, delete 라는 단어도 불필요한 동사 어구 처리라고 보시면 되겠습니다!~

2023-01-25 05:09 UTC, kyeongraekim commented on sooyoung/db/migrations/20230123075429_create_likes_table.sql
> +
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2023-01-25 08:50 UTC, fromSYHwang commented on sooyoung/db/migrations/20230123075429_create_likes_table.sql
> +
말씀해주신 부분을 추가했습니다! 그런데 likes에 UNIQUE 제약조건을 추가했더니 이미 좋아요 한 게시물에 동일 사용자가 다시 좋아요 요청을 보내면 sql 엔트리 중복이라는 에러와 함께 서버가 종료되는데 제대로 된 걸까요?

2023-01-26 01:31 UTC, kyeongraekim requested changes

2023-01-26 01:31 UTC, kyeongraekim commented on sooyoung/db/migrations/20230123075429_create_likes_table.sql
> +
네 맞습니다. sql 엔트리 중복 에러를 일부러 의도해야 하는게 맞고, 데이터베이스에 해당 데이터가 들어가지 않도록 해야되는게 맞습니다. 

express 어플리케이션 단에서의 로직 선에서, 중복 선택시 해당 내용을 삭제하는 로직이 추가로 필요한 부분이라고 보시면 되겠습니다!

2023-01-26 01:43 UTC, kyeongraekim commented on sooyoung/db/migrations/20230123075429_create_likes_table.sql
> +
```
ALTER TABLE likes ADD CONSTRAINT constraint_likes_unique UNIQUE (user_id, post_id);

2023-01-26 02:48 UTC, kyeongraekim approved these changes
LGTM!~

2023-01-26 02:48 UTC, merged