[박세희] Assignment 3 : Express API CRUD - 게시물 등록
wecode-bootcamp-korea/42-backend-westagram-2 pull request #8
Opened 2023-01-20 12:46 UTC by sayhihi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 게시물 등록 및 유저 id값  데이터베이스 저장 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
유저가 등록한 게시글 저장 
status : 201  message :  "postCreated"

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![post:posting server connection](https://user-images.githubusercontent.com/117356735/213698152-98482673-d31d-43a6-b88e-6898dbeded3f.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지

<img width="694" alt="POSTMAN-posting " src="https://user-images.githubusercontent.com/117356735/213698190-bd964ed4-4760-4a64-abfe-a8981a37ac62.png">

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

![post:posting table](https://user-images.githubusercontent.com/117356735/213698175-3962b628-f896-4658-8e30-fd5cb4cf523c.png)

<br />

## :: 기타 질문 및 특이 사항

2023-01-25 05:12 UTC, kyeongraekim requested changes

2023-01-25 05:12 UTC, kyeongraekim commented on sehee/app.js
> +app.post("/post/posting", async (req, res) => {
- RESTful 한 엔드포인트 설계법에 맞게 /posting 정도로 설정한 후 post라는 http 메소드를 설정해주시면 게시물에 대한 정보를 바디에 담아서 디비에 저장하겠다는 의미로 개발자들은 이해할 수 있습니다. 
- 따라서 "/post/posting" -> "/posting" 으로 수정해도 무방할 것 같습니다!

2023-01-26 01:40 UTC, kyeongraekim requested changes

2023-01-26 01:40 UTC, kyeongraekim commented on sehee/app.js
> +});
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM posts`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const posts = await myDataSource.query(`SELECT * FROM posts`);
      
      res.status(200).json({ data : posts})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

2023-01-26 01:40 UTC, kyeongraekim commented on sehee/db/migrations/20230125075041_create_likes_table.sql
> +);
제가 리뷰시 의도드렸던 바는 아래와 같은 형태와 같습니다! 아래의 내용을 찬찬히 고민해서 살펴보시고 의도를 코멘트로 함께 남겨주세요!

```
ALTER TABLE likes ADD CONSTRAINT constraint_likes_unique UNIQUE (user_id, post_id);

2023-01-26 05:13 UTC, sayhihi commented on sehee/db/migrations/20230125075041_create_likes_table.sql
> +);
likes 에서 의도하신 내용은 좋아요를 한 게시물당 유저가 한번만 누를 수 있기 때문에 unique를 사용해야 한다고 생각합니다. 
제출 전에 mysql에서 unique를 추가적으로 작성 했었고, 좋아요 게시글도 중복적으로 입력이 안되는 것을 확인했습니다.
정확하게 적용된 건지 여부는 아직 잘 판단되지 않아 인덱스 조회 결과 첨부해드립니다.

![스크린샷 2023-01-26 오후 1 58 47](https://user-images.githubusercontent.com/117356735/214762987-d9067af9-34a8-4fc4-b29f-13a84f866e22.png)

2023-01-26 05:26 UTC, kyeongraekim approved these changes
LGTM!~ 레이어드 패턴 이어서 적용해서 푸시해주세요!~

2023-01-26 05:26 UTC, merged